version: 1.0.{build}

image:
  - Visual Studio 2022

environment:
  matrix:
    - platform: x64

install:
  - vcpkg install openssl4:x64-windows

before_build:
  - cmake -G "Visual Studio 17 2022" -A %platform% -DCMAKE_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake .

build:
  project: ALL_BUILD.vcxproj
  parallel: true
  verbosity: minimal

artifacts:
  - path: '**\Release\*.exe'
